# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(250, 250))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Intel = QtWidgets.QWidget()
        self.Intel.setObjectName("Intel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Intel)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchFrame = QtWidgets.QFrame(self.Intel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchFrame.sizePolicy().hasHeightForWidth())
        self.searchFrame.setSizePolicy(sizePolicy)
        self.searchFrame.setMaximumSize(QtCore.QSize(5000, 5000))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.charSearch = QtWidgets.QLineEdit(self.searchFrame)
        self.charSearch.setObjectName("charSearch")
        self.horizontalLayout.addWidget(self.charSearch)
        self.searchBtn = QtWidgets.QPushButton(self.searchFrame)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lcdNumber = QtWidgets.QLCDNumber(self.searchFrame)
        self.lcdNumber.setAutoFillBackground(False)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.verticalLayout_2.addWidget(self.searchFrame)
        self.frame_2 = QtWidgets.QFrame(self.Intel)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.charDetail = QtWidgets.QToolBox(self.frame_2)
        self.charDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.charDetail.setFrameShadow(QtWidgets.QFrame.Plain)
        self.charDetail.setObjectName("charDetail")
        self.summary = QtWidgets.QWidget()
        self.summary.setGeometry(QtCore.QRect(0, 0, 437, 413))
        self.summary.setObjectName("summary")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.summary)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.charName = QtWidgets.QLabel(self.summary)
        self.charName.setObjectName("charName")
        self.verticalLayout_5.addWidget(self.charName)
        self.corpName = QtWidgets.QLabel(self.summary)
        self.corpName.setObjectName("corpName")
        self.verticalLayout_5.addWidget(self.corpName)
        self.corpMembers = QtWidgets.QLabel(self.summary)
        self.corpMembers.setObjectName("corpMembers")
        self.verticalLayout_5.addWidget(self.corpMembers)
        self.secStatus = QtWidgets.QLabel(self.summary)
        self.secStatus.setObjectName("secStatus")
        self.verticalLayout_5.addWidget(self.secStatus)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.summary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 417, 72))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.charBio = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.charBio.setWordWrap(True)
        self.charBio.setObjectName("charBio")
        self.verticalLayout_9.addWidget(self.charBio)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.charDetail.addItem(self.summary, "")
        self.charInfo = QtWidgets.QWidget()
        self.charInfo.setGeometry(QtCore.QRect(0, 0, 437, 413))
        self.charInfo.setObjectName("charInfo")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.charInfo)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.charInfo)
        self.frame.setMinimumSize(QtCore.QSize(0, 128))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.charLogo = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charLogo.sizePolicy().hasHeightForWidth())
        self.charLogo.setSizePolicy(sizePolicy)
        self.charLogo.setMaximumSize(QtCore.QSize(128, 128))
        self.charLogo.setText("")
        self.charLogo.setScaledContents(True)
        self.charLogo.setObjectName("charLogo")
        self.horizontalLayout_2.addWidget(self.charLogo, 0, QtCore.Qt.AlignLeft)
        self.corpLogo = QtWidgets.QLabel(self.frame)
        self.corpLogo.setMaximumSize(QtCore.QSize(128, 128))
        self.corpLogo.setText("")
        self.corpLogo.setScaledContents(True)
        self.corpLogo.setObjectName("corpLogo")
        self.horizontalLayout_2.addWidget(self.corpLogo)
        self.allianceLogo = QtWidgets.QLabel(self.frame)
        self.allianceLogo.setMaximumSize(QtCore.QSize(128, 128))
        self.allianceLogo.setText("")
        self.allianceLogo.setScaledContents(True)
        self.allianceLogo.setObjectName("allianceLogo")
        self.horizontalLayout_2.addWidget(self.allianceLogo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_6.addWidget(self.frame)
        self.charName_2 = QtWidgets.QLabel(self.charInfo)
        self.charName_2.setObjectName("charName_2")
        self.verticalLayout_6.addWidget(self.charName_2)
        self.secStatus_2 = QtWidgets.QLabel(self.charInfo)
        self.secStatus_2.setWordWrap(False)
        self.secStatus_2.setObjectName("secStatus_2")
        self.verticalLayout_6.addWidget(self.secStatus_2)
        self.scrollArea = QtWidgets.QScrollArea(self.charInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 417, 81))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.charBio_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.charBio_2.setWordWrap(True)
        self.charBio_2.setObjectName("charBio_2")
        self.verticalLayout_8.addWidget(self.charBio_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.charDetail.addItem(self.charInfo, "")
        self.corpInfo = QtWidgets.QWidget()
        self.corpInfo.setGeometry(QtCore.QRect(0, 0, 437, 413))
        self.corpInfo.setObjectName("corpInfo")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.corpInfo)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.corpInfo)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 128))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.corpLogo_2 = QtWidgets.QLabel(self.frame_3)
        self.corpLogo_2.setMaximumSize(QtCore.QSize(128, 128))
        self.corpLogo_2.setText("")
        self.corpLogo_2.setScaledContents(True)
        self.corpLogo_2.setWordWrap(False)
        self.corpLogo_2.setObjectName("corpLogo_2")
        self.horizontalLayout_3.addWidget(self.corpLogo_2)
        self.allianceLogo_2 = QtWidgets.QLabel(self.frame_3)
        self.allianceLogo_2.setMaximumSize(QtCore.QSize(128, 128))
        self.allianceLogo_2.setText("")
        self.allianceLogo_2.setScaledContents(True)
        self.allianceLogo_2.setWordWrap(False)
        self.allianceLogo_2.setObjectName("allianceLogo_2")
        self.horizontalLayout_3.addWidget(self.allianceLogo_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.corpName_2 = QtWidgets.QLabel(self.corpInfo)
        self.corpName_2.setWordWrap(True)
        self.corpName_2.setObjectName("corpName_2")
        self.verticalLayout_7.addWidget(self.corpName_2)
        self.alliance = QtWidgets.QLabel(self.corpInfo)
        self.alliance.setText("")
        self.alliance.setWordWrap(True)
        self.alliance.setObjectName("alliance")
        self.verticalLayout_7.addWidget(self.alliance)
        self.corpMembers_2 = QtWidgets.QLabel(self.corpInfo)
        self.corpMembers_2.setWordWrap(True)
        self.corpMembers_2.setObjectName("corpMembers_2")
        self.verticalLayout_7.addWidget(self.corpMembers_2)
        self.corpCeo = QtWidgets.QLabel(self.corpInfo)
        self.corpCeo.setWordWrap(True)
        self.corpCeo.setObjectName("corpCeo")
        self.verticalLayout_7.addWidget(self.corpCeo)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.corpInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.scrollArea_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 415, 69))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.corpDescription = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.corpDescription.setText("")
        self.corpDescription.setWordWrap(True)
        self.corpDescription.setObjectName("corpDescription")
        self.verticalLayout_10.addWidget(self.corpDescription)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.addWidget(self.scrollArea_3)
        self.charDetail.addItem(self.corpInfo, "")
        self.verticalLayout_4.addWidget(self.charDetail)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tabWidget.addTab(self.Intel, "")
        self.Notes = QtWidgets.QWidget()
        self.Notes.setObjectName("Notes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Notes)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.noteTaker = QtWidgets.QPlainTextEdit(self.Notes)
        self.noteTaker.setFrameShadow(QtWidgets.QFrame.Raised)
        self.noteTaker.setObjectName("noteTaker")
        self.verticalLayout_3.addWidget(self.noteTaker)
        self.tabWidget.addTab(self.Notes, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setEnabled(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSupport = QtWidgets.QAction(MainWindow)
        self.actionSupport.setEnabled(True)
        self.actionSupport.setObjectName("actionSupport")
        self.actionCheck_for_Updates = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_Updates.setEnabled(False)
        self.actionCheck_for_Updates.setObjectName("actionCheck_for_Updates")
        self.action_Bug_Report = QtWidgets.QAction(MainWindow)
        self.action_Bug_Report.setEnabled(False)
        self.action_Bug_Report.setObjectName("action_Bug_Report")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionSupport)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCheck_for_Updates)
        self.menuHelp.addAction(self.action_Bug_Report)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.charDetail.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eve Intel Tool"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
        self.charName.setText(_translate("MainWindow", "Name: "))
        self.corpName.setText(_translate("MainWindow", "Corporation Name: "))
        self.corpMembers.setText(_translate("MainWindow", "Corporation Members: "))
        self.secStatus.setText(_translate("MainWindow", "Security Status: "))
        self.charBio.setText(_translate("MainWindow", "Bio: "))
        self.charDetail.setItemText(self.charDetail.indexOf(self.summary), _translate("MainWindow", "Summary"))
        self.charName_2.setText(_translate("MainWindow", "Name: "))
        self.secStatus_2.setText(_translate("MainWindow", "Security Status: "))
        self.charDetail.setItemText(self.charDetail.indexOf(self.charInfo), _translate("MainWindow", "Character Information"))
        self.corpName_2.setText(_translate("MainWindow", "Corporation Name: "))
        self.corpMembers_2.setText(_translate("MainWindow", "Member Count: "))
        self.corpCeo.setText(_translate("MainWindow", "CEO: "))
        self.charDetail.setItemText(self.charDetail.indexOf(self.corpInfo), _translate("MainWindow", "Corporation Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Intel), _translate("MainWindow", "Intel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Notes), _translate("MainWindow", "Notes"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "&Save.."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen.setText(_translate("MainWindow", "&Open.."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSupport.setText(_translate("MainWindow", "&Support"))
        self.actionCheck_for_Updates.setText(_translate("MainWindow", "&Check for Updates"))
        self.action_Bug_Report.setText(_translate("MainWindow", "&Bug Report"))

